# https://github.com/travis-perl/helpers
language: perl
env:
  global:
    - COVERAGE=0
    - AUTHOR_TESTING=0
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
  - "5.32"
  - "blead"
sudo: false
matrix:
  include:
    - perl: "5.32"
      env: COVERAGE=1
  allow_failures:
    - perl: "blead"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -lrv -j$((SYSTEM_CORES + 1)) $(test-dirs)
after_success:
  - coverage-report
